# .github/FUNDING.yml
# This adds a Sponsor button to your hellocall repository

# GitHub Sponsors (official GitHub option)

# Optional custom link for one-time support ($10)
custom: ["https://github.com/sponsors/prioumprioum728-create?frequency=one-time&amount=10"]
