# .github/FUNDING.yml

# GitHub Sponsors
github: ["YOUR_GITHUB_USERNAME"]

# Optional: custom link (like family/friends help)
custom: ["https://github.com/sponsors/YOUR_GITHUB_USERNAME?frequency=one-time&amount=10"]
