name: Build & Deploy HelloCall Website

on:
  push:
    branches: [ main ]       # Runs when you push to main
  workflow_dispatch:          # Allows manual run from GitHub Actions tab

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout your repository
      - name: Checkout Repo
        uses: actions/checkout@v4

      # 2️⃣ Run HelloCall Website Builder Action
      - name: Build HelloCall Website
        uses: ./action.yml          # Your builder action in root
        with:
          site_title: "HelloCall OS"
          theme_color: "blue"

      # 3️⃣ Deploy to Firebase Hosting
      - name: Firebase Deployment CLI
        uses: jmsalazardev/firebase-deploy@v0.0.3
        with:
          project_id: ${{ secrets.FIREBASE_PROJECT_ID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          only: hosting

      # 4️⃣ Deploy to GitHub Pages (backup)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./          # publish root folder, adjust if needed
          publish_branch: gh-pages
